version: '3'
services:
  app:
    build: .
    container_name: Sample_Camera
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - .:/src/app
    working_dir: /src/app
    command: npm run dev