version: '3'
services:
  app:
    image: node:lts-alpine3.16
    container_name: Sample_Camera
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app
    working_dir: /app
    command: npm run dev