services:
  app:
    build: .
    container_name: 'Sample_Camera'
    volumes: 
      - .:/src/mnt
    ports:
      - '3000:3000'
    tty: true
    working_dir: /src/mnt
    command: /bin/sh -c "while :; do sleep 10; done"

